// <auto-generated />
using System;
using Honeydew.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Honeydew.Migrations
{
    [DbContext(typeof(HoneydewDbContext))]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Honeydew.Entities.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");
                    b.Property<string>("ClientId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");
                    b.Property<string>("ClientSecretHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");
                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ClientId")
                        .IsUnique();
                    b.HasIndex("TenantId");
                    b.ToTable("ApiClients");
                });

            modelBuilder.Entity("Honeydew.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");
                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    b.Property<string>("SettingsJson")
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Name");
                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Honeydew.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");
                    b.Property<bool>("CanEditAllTodos")
                        .HasColumnType("INTEGER");
                    b.Property<bool>("CanViewAllTodos")
                        .HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");
                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");
                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");
                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");
                    b.Property<string>("PasswordSalt")
                        .HasColumnType("TEXT");
                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("TenantId", "Email")
                        .IsUnique();
                    b.ToTable("Users");
                });

            modelBuilder.Entity("Honeydew.Entities.ApiClient", b =>
                {
                    b.HasOne("Honeydew.Entities.Tenant", "Tenant")
                        .WithMany("ApiClients")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Honeydew.Entities.User", b =>
                {
                    b.HasOne("Honeydew.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Honeydew.Entities.Tenant", b =>
                {
                    b.Navigation("ApiClients");
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
